### PR TITLE
Devhawk/slurp

### PR DESCRIPTION
**Pull request by devhawk**
Add methods to slurp helpful OKH and OKW YAML files into in memory object. Works with local files and files loaded via URLs

### CODE REVIEW

**Comment by Jbutler-helpful** [comment]
What are the Poetry check failures?

**Review by Jbutler-helpful — APPROVED** [review]
This looks reasonable to me.

**Comment by devhawk** [comment]
> What are the Poetry check failures?

We are going to merge w/o fixing Poetry. There's an outstanding PR (likely out of date at this point) for updating poetry

**Comment by Jbutler-helpful** [comment]
@devhawk is this done?

**Pull request merged**
